function T = qualityThresholds()
%QUALITYTHRESHOLDS Default (fail_below, borderline_below) per quality criterion.
%
%   Scores are in [0, 1] and higher is always better. Field order is the order
%   the criteria are evaluated and reported in, and matches the Python gate.

T = struct( ...
    'focus',          [0.25 0.50], ...
    'illumination',   [0.30 0.55], ...
    'contrast',       [0.25 0.50], ...
    'fov',            [0.55 0.80], ...
    'macula',         [0.20 0.45], ...
    'artifact',       [0.30 0.60], ...
    'under_exposure', [0.25 0.50], ...
    'over_exposure',  [0.25 0.50], ...
    'noise',          [0.20 0.45]);
end
