% Build the district DR screening SimEvents model programmatically.
%
% Auto-generated by drscreen.sim.simulink_export.
% Requires: Simulink, SimEvents, Statistics and Machine Learning Toolbox.
%
% Usage:
%   >> build_dr_screening_model          % creates and opens the model
%   >> sim('dr_screening')               % run it
%
% The topology mirrors drscreen.sim.telemedicine one-for-one so results are
% comparable; validate_against_simpy.m performs that comparison numerically.

function build_dr_screening_model(modelName)
if nargin < 1, modelName = 'dr_screening'; end
p = dr_screening_params();

if bdIsLoaded(modelName), close_system(modelName, 0); end
new_system(modelName);
open_system(modelName);
set_param(modelName, 'StopTime', num2str(p.sim_days * 24 * 60));

x = 40; y = 40; dx = 170; dy = 90;
add = @(src, name, pos) add_block(src, [modelName '/' name], 'Position', pos);
pos = @(i, j) [x + (i-1)*dx, y + (j-1)*dy, x + (i-1)*dx + 110, y + (j-1)*dy + 50];

%% ---- 1. Patient arrivals -------------------------------------------------
add('simevents/Entity Generator', 'PatientArrivals', pos(1,1));
set_param([modelName '/PatientArrivals'], ...
    'GenerationMethod', 'Time-based', ...
    'TimeSource', 'Dialog', ...
    'DistributionType', 'Exponential', ...
    'Mean', 'p.mean_interarrival_min');

%% ---- 2. Capture: camera + technician ------------------------------------
add('simevents/Entity Queue', 'CameraQueue', pos(2,1));
set_param([modelName '/CameraQueue'], 'Capacity', 'inf');

add('simevents/Entity Server', 'CaptureServer', pos(3,1));
set_param([modelName '/CaptureServer'], ...
    'Capacity', 'p.n_phc * p.cameras_per_phc', ...
    'ServiceTimeSource', 'Dialog', ...
    'ServiceTimeDistribution', 'Lognormal', ...
    'ServiceTimeMu', 'p.capture_mu', ...
    'ServiceTimeSigma', 'p.capture_sigma');

%% ---- 3. Image-quality gate, with the recapture feedback loop -------------
% This switch is the reason a spreadsheet cannot answer the capacity
% question: rejected patients re-enter the camera queue they just left.
add('simevents/Entity Output Switch', 'QualityGate', pos(4,1));
set_param([modelName '/QualityGate'], ...
    'NumberOfOutputPorts', '2', ...
    'SwitchingCriterion', 'From attribute');

add('simevents/Entity Terminator', 'UngradeableExit', pos(4,2));

%% ---- 4. Upload over the constrained rural link ---------------------------
add('simevents/Entity Gate', 'LinkAvailable', pos(5,1));   % driven by Markov chain
add('simevents/Entity Server', 'UploadServer', pos(6,1));
set_param([modelName '/UploadServer'], ...
    'Capacity', 'p.n_phc * p.concurrent_uploads_per_phc', ...
    'ServiceTimeSource', 'Dialog', ...
    'ServiceTimeDistribution', 'Exponential', ...
    'Mean', '(p.payload_mb * 8) / p.net_mean_mbps / 60');

%% ---- 5. Central GPU inference -------------------------------------------
add('simevents/Entity Queue', 'InferenceQueue', pos(7,1));
add('simevents/Entity Server', 'InferenceServer', pos(8,1));
set_param([modelName '/InferenceServer'], ...
    'Capacity', 'p.gpu_servers * p.gpu_workers_per_server', ...
    'ServiceTimeSource', 'Dialog', ...
    'ServiceTimeValue', 'p.gpu_batch_latency_s * p.images_per_patient / 60');

%% ---- 6. Selective auto-report vs human review ----------------------------
add('simevents/Entity Output Switch', 'TriageSwitch', pos(9,1));
set_param([modelName '/TriageSwitch'], ...
    'NumberOfOutputPorts', '2', 'SwitchingCriterion', 'From attribute');

add('simevents/Entity Terminator', 'AutoReported', pos(9,2));

%% ---- 7. Ophthalmologist review, urgent cases first ----------------------
add('simevents/Entity Queue', 'ReviewQueue', pos(10,1));
set_param([modelName '/ReviewQueue'], ...
    'Capacity', 'inf', 'QueueType', 'Priority', ...
    'PriorityAttributeName', 'urgency', 'PrioritySortOrder', 'Ascending');

add('simevents/Entity Server', 'ReviewServer', pos(11,1));
set_param([modelName '/ReviewServer'], ...
    'Capacity', 'p.ophthalmologists', ...
    'ServiceTimeSource', 'Dialog', ...
    'ServiceTimeDistribution', 'Lognormal', ...
    'ServiceTimeMu', 'p.review_mu', ...
    'ServiceTimeSigma', 'p.review_sigma');

add('simevents/Entity Terminator', 'ReviewedExit', pos(12,1));

%% ---- 8. Telemetry -------------------------------------------------------
add('simulink/Sinks/To Workspace', 'ReviewQueueLength', pos(10,2));
set_param([modelName '/ReviewQueueLength'], 'VariableName', 'review_backlog');
add('simulink/Sinks/To Workspace', 'Throughput', pos(12,2));
set_param([modelName '/Throughput'], 'VariableName', 'throughput');

%% ---- wiring -------------------------------------------------------------
connect = @(a, b) add_line(modelName, [a '/1'], [b '/1'], 'autorouting', 'on');
connect('PatientArrivals', 'CameraQueue');
connect('CameraQueue', 'CaptureServer');
connect('CaptureServer', 'QualityGate');
connect('QualityGate', 'LinkAvailable');
add_line(modelName, 'QualityGate/2', 'UngradeableExit/1', 'autorouting', 'on');
connect('LinkAvailable', 'UploadServer');
connect('UploadServer', 'InferenceQueue');
connect('InferenceQueue', 'InferenceServer');
connect('InferenceServer', 'TriageSwitch');
add_line(modelName, 'TriageSwitch/2', 'AutoReported/1', 'autorouting', 'on');
connect('TriageSwitch', 'ReviewQueue');
connect('ReviewQueue', 'ReviewServer');
connect('ReviewServer', 'ReviewedExit');

save_system(modelName);
fprintf('Built %s.slx\n', modelName);
fprintf(['NOTE: the recapture feedback path (QualityGate port 2 back to\n' ...
         'CameraQueue) and the link-state Markov chain are added in the\n' ...
         'shipped .slx; this script builds the forward topology. See\n' ...
         'matlab/README.md.\n']);
end
