% Auto-generated by drscreen.sim.simulink_export -- do not edit by hand.
% Single source of truth: drscreen.sim.telemedicine.SimConfig
%
% Time base: MINUTES throughout, matching the SimPy model.

function p = dr_screening_params()

p.annual_patients = 100000;
p.n_phc = 12;
p.working_days_per_year = 250;
p.hours_per_day = 7.0;
p.cameras_per_phc = 1;
p.technicians_per_phc = 1;
p.capture_time_min = 4.0;
p.capture_time_cv = 0.35;
p.images_per_patient = 2;
p.image_mb = 3.2;
p.edge_iqa = true;
p.edge_iqa_latency_s = 0.35;
p.ungradeable_rate = 0.12;
p.recapture_success_rate = 0.75;
p.max_recaptures = 2;
p.network = '3g';
p.concurrent_uploads_per_phc = 2;
p.upload_retries = 3;
p.edge_inference = false;
p.edge_inference_s = 2.8;
p.gpu_servers = 2;
p.gpu_batch_latency_s = 0.45;
p.gpu_workers_per_server = 4;
p.ophthalmologists = 2.0;
p.review_hours_per_day = 5.0;
p.review_time_min = 0.5;
p.review_time_min_unaided = 2.5;
p.auto_report_coverage = 0.7;
p.review_time_cv = 0.4;
p.prevalence_referable = 0.18;
p.prevalence_urgent = 0.045;
p.sla_days_routine = 14.0;
p.sla_days_urgent = 2.0;
p.sim_days = 250;
p.seed = 0;
p.warmup_days = 10;

% -- derived quantities -------------------------------------------
p.patients_per_phc_per_day = p.annual_patients / (p.n_phc * p.working_days_per_year);
p.mean_interarrival_min = (p.hours_per_day * 60) / p.patients_per_phc_per_day;
p.payload_mb = p.image_mb * p.images_per_patient;

% -- network profile ----------------------------------------------
p.net_mean_mbps = 1.6;
p.net_cv = 0.55;
p.net_availability = 0.9;
p.net_outage_mean_min = 15.0;
% Mean uptime chosen so the stationary up-fraction equals availability.
p.net_uptime_mean_min = p.net_outage_mean_min * p.net_availability / (1 - p.net_availability);

% -- lognormal service-time parameters (MATLAB uses mu, sigma of log) --
p.capture_sigma = sqrt(log(1 + p.capture_time_cv^2));
p.capture_mu = log(p.capture_time_min) - p.capture_sigma^2/2;
p.review_sigma = sqrt(log(1 + p.review_time_cv^2));
p.review_mu = log(p.review_time_min) - p.review_sigma^2/2;

end
