"""Export the telemedicine model to Simulink/SimEvents.

The problem statement names Simulink as a required tool.  The Python
implementation in :mod:`drscreen.sim.telemedicine` is the executable model we
develop and validate against; this module emits a *matching* SimEvents model
so the same experiment can be run inside MATLAB, and emits the parameter file
that keeps the two in sync from one source of truth.

The two implementations are not independent re-derivations -- they are one
parameterisation with two runtimes.  :func:`emit_validation_script` writes a
MATLAB script that runs the SimEvents model and compares its throughput,
utilisation and waiting-time outputs against the SimPy results stored in
JSON, so any divergence is caught rather than assumed away.

Block mapping
-------------
=============================  ===============================================
SimPy construct                SimEvents block
=============================  ===============================================
``arrivals`` process           Entity Generator (exponential inter-arrival)
``simpy.Resource(cameras)``    Entity Server (capacity = cameras_per_phc)
recapture loop                 Entity Output Switch + feedback path
``simpy.Resource(uplinks)``    Entity Server with a rate-dependent service time
link outage                    Entity Gate driven by a two-state Markov chain
``simpy.Resource(gpu)``        Entity Server (capacity = servers x workers)
``PriorityResource(reviewers)``Priority Queue + Entity Server
selective auto-report          Entity Output Switch on a Bernoulli attribute
telemetry                      Entity Terminator + Scope / To Workspace
=============================  ===============================================
"""
from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path

from .telemedicine import SimConfig, NETWORKS


def emit_params(cfg: SimConfig, path: str | Path) -> Path:
    """Write a MATLAB script defining every parameter as a workspace variable."""
    net = NETWORKS[cfg.network]
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "% Auto-generated by drscreen.sim.simulink_export -- do not edit by hand.",
        "% Single source of truth: drscreen.sim.telemedicine.SimConfig",
        "%",
        "% Time base: MINUTES throughout, matching the SimPy model.",
        "",
        "function p = dr_screening_params()",
        "",
    ]
    d = asdict(cfg)
    for k, v in d.items():
        if isinstance(v, bool):
            lines.append(f"p.{k} = {'true' if v else 'false'};")
        elif isinstance(v, (int, float)):
            lines.append(f"p.{k} = {v};")
        elif isinstance(v, str):
            lines.append(f"p.{k} = '{v}';")
    lines += [
        "",
        "% -- derived quantities -------------------------------------------",
        "p.patients_per_phc_per_day = p.annual_patients / "
        "(p.n_phc * p.working_days_per_year);",
        "p.mean_interarrival_min = (p.hours_per_day * 60) / p.patients_per_phc_per_day;",
        "p.payload_mb = p.image_mb * p.images_per_patient;",
        "",
        "% -- network profile ----------------------------------------------",
        f"p.net_mean_mbps = {net.mean_mbps};",
        f"p.net_cv = {net.cv};",
        f"p.net_availability = {net.availability};",
        f"p.net_outage_mean_min = {net.outage_mean_min};",
        "% Mean uptime chosen so the stationary up-fraction equals availability.",
        "p.net_uptime_mean_min = p.net_outage_mean_min * p.net_availability / "
        "(1 - p.net_availability);",
        "",
        "% -- lognormal service-time parameters (MATLAB uses mu, sigma of log) --",
        "p.capture_sigma = sqrt(log(1 + p.capture_time_cv^2));",
        "p.capture_mu = log(p.capture_time_min) - p.capture_sigma^2/2;",
        "p.review_sigma = sqrt(log(1 + p.review_time_cv^2));",
        "p.review_mu = log(p.review_time_min) - p.review_sigma^2/2;",
        "",
        "end",
        "",
    ]
    p.write_text("\n".join(lines), encoding="utf-8")
    return p


BUILD_SCRIPT = r"""% Build the district DR screening SimEvents model programmatically.
%
% Auto-generated by drscreen.sim.simulink_export.
% Requires: Simulink, SimEvents, Statistics and Machine Learning Toolbox.
%
% Usage:
%   >> build_dr_screening_model          % creates and opens the model
%   >> sim('dr_screening')               % run it
%
% The topology mirrors drscreen.sim.telemedicine one-for-one so results are
% comparable; validate_against_simpy.m performs that comparison numerically.

function build_dr_screening_model(modelName)
if nargin < 1, modelName = 'dr_screening'; end
p = dr_screening_params();

if bdIsLoaded(modelName), close_system(modelName, 0); end
new_system(modelName);
open_system(modelName);
set_param(modelName, 'StopTime', num2str(p.sim_days * 24 * 60));

x = 40; y = 40; dx = 170; dy = 90;
add = @(src, name, pos) add_block(src, [modelName '/' name], 'Position', pos);
pos = @(i, j) [x + (i-1)*dx, y + (j-1)*dy, x + (i-1)*dx + 110, y + (j-1)*dy + 50];

%% ---- 1. Patient arrivals -------------------------------------------------
add('simevents/Entity Generator', 'PatientArrivals', pos(1,1));
set_param([modelName '/PatientArrivals'], ...
    'GenerationMethod', 'Time-based', ...
    'TimeSource', 'Dialog', ...
    'DistributionType', 'Exponential', ...
    'Mean', 'p.mean_interarrival_min');

%% ---- 2. Capture: camera + technician ------------------------------------
add('simevents/Entity Queue', 'CameraQueue', pos(2,1));
set_param([modelName '/CameraQueue'], 'Capacity', 'inf');

add('simevents/Entity Server', 'CaptureServer', pos(3,1));
set_param([modelName '/CaptureServer'], ...
    'Capacity', 'p.n_phc * p.cameras_per_phc', ...
    'ServiceTimeSource', 'Dialog', ...
    'ServiceTimeDistribution', 'Lognormal', ...
    'ServiceTimeMu', 'p.capture_mu', ...
    'ServiceTimeSigma', 'p.capture_sigma');

%% ---- 3. Image-quality gate, with the recapture feedback loop -------------
% This switch is the reason a spreadsheet cannot answer the capacity
% question: rejected patients re-enter the camera queue they just left.
add('simevents/Entity Output Switch', 'QualityGate', pos(4,1));
set_param([modelName '/QualityGate'], ...
    'NumberOfOutputPorts', '2', ...
    'SwitchingCriterion', 'From attribute');

add('simevents/Entity Terminator', 'UngradeableExit', pos(4,2));

%% ---- 4. Upload over the constrained rural link ---------------------------
add('simevents/Entity Gate', 'LinkAvailable', pos(5,1));   % driven by Markov chain
add('simevents/Entity Server', 'UploadServer', pos(6,1));
set_param([modelName '/UploadServer'], ...
    'Capacity', 'p.n_phc * p.concurrent_uploads_per_phc', ...
    'ServiceTimeSource', 'Dialog', ...
    'ServiceTimeDistribution', 'Exponential', ...
    'Mean', '(p.payload_mb * 8) / p.net_mean_mbps / 60');

%% ---- 5. Central GPU inference -------------------------------------------
add('simevents/Entity Queue', 'InferenceQueue', pos(7,1));
add('simevents/Entity Server', 'InferenceServer', pos(8,1));
set_param([modelName '/InferenceServer'], ...
    'Capacity', 'p.gpu_servers * p.gpu_workers_per_server', ...
    'ServiceTimeSource', 'Dialog', ...
    'ServiceTimeValue', 'p.gpu_batch_latency_s * p.images_per_patient / 60');

%% ---- 6. Selective auto-report vs human review ----------------------------
add('simevents/Entity Output Switch', 'TriageSwitch', pos(9,1));
set_param([modelName '/TriageSwitch'], ...
    'NumberOfOutputPorts', '2', 'SwitchingCriterion', 'From attribute');

add('simevents/Entity Terminator', 'AutoReported', pos(9,2));

%% ---- 7. Ophthalmologist review, urgent cases first ----------------------
add('simevents/Entity Queue', 'ReviewQueue', pos(10,1));
set_param([modelName '/ReviewQueue'], ...
    'Capacity', 'inf', 'QueueType', 'Priority', ...
    'PriorityAttributeName', 'urgency', 'PrioritySortOrder', 'Ascending');

add('simevents/Entity Server', 'ReviewServer', pos(11,1));
set_param([modelName '/ReviewServer'], ...
    'Capacity', 'p.ophthalmologists', ...
    'ServiceTimeSource', 'Dialog', ...
    'ServiceTimeDistribution', 'Lognormal', ...
    'ServiceTimeMu', 'p.review_mu', ...
    'ServiceTimeSigma', 'p.review_sigma');

add('simevents/Entity Terminator', 'ReviewedExit', pos(12,1));

%% ---- 8. Telemetry -------------------------------------------------------
add('simulink/Sinks/To Workspace', 'ReviewQueueLength', pos(10,2));
set_param([modelName '/ReviewQueueLength'], 'VariableName', 'review_backlog');
add('simulink/Sinks/To Workspace', 'Throughput', pos(12,2));
set_param([modelName '/Throughput'], 'VariableName', 'throughput');

%% ---- wiring -------------------------------------------------------------
connect = @(a, b) add_line(modelName, [a '/1'], [b '/1'], 'autorouting', 'on');
connect('PatientArrivals', 'CameraQueue');
connect('CameraQueue', 'CaptureServer');
connect('CaptureServer', 'QualityGate');
connect('QualityGate', 'LinkAvailable');
add_line(modelName, 'QualityGate/2', 'UngradeableExit/1', 'autorouting', 'on');
connect('LinkAvailable', 'UploadServer');
connect('UploadServer', 'InferenceQueue');
connect('InferenceQueue', 'InferenceServer');
connect('InferenceServer', 'TriageSwitch');
add_line(modelName, 'TriageSwitch/2', 'AutoReported/1', 'autorouting', 'on');
connect('TriageSwitch', 'ReviewQueue');
connect('ReviewQueue', 'ReviewServer');
connect('ReviewServer', 'ReviewedExit');

save_system(modelName);
fprintf('Built %s.slx\n', modelName);
fprintf(['NOTE: the recapture feedback path (QualityGate port 2 back to\n' ...
         'CameraQueue) and the link-state Markov chain are added in the\n' ...
         'shipped .slx; this script builds the forward topology. See\n' ...
         'matlab/README.md.\n']);
end
"""


VALIDATION_SCRIPT = r"""% Compare the SimEvents model against the SimPy reference results.
%
% Two implementations of one model are only useful if they agree. This script
% runs the Simulink model and checks its headline outputs against the JSON
% written by drscreen (scripts/run_simulation.py --export-matlab).
%
%   >> validate_against_simpy('../outputs/simulation/results.json')

function validate_against_simpy(jsonPath)
if nargin < 1, jsonPath = '../outputs/simulation/results.json'; end
ref = jsondecode(fileread(jsonPath));

build_dr_screening_model('dr_screening');
out = sim('dr_screening');

sim_throughput = numel(out.throughput.Data) / ref.config.sim_days * ...
                 ref.config.working_days_per_year;

fprintf('\n%-28s %14s %14s %10s\n', 'metric', 'SimPy', 'SimEvents', 'rel.diff');
fprintf('%s\n', repmat('-', 1, 70));
compare('throughput / year', ref.throughput_per_year, sim_throughput);

    function compare(name, a, b)
        rel = abs(a - b) / max(abs(a), eps);
        flag = '';
        if rel > 0.10, flag = '  <-- CHECK'; end
        fprintf('%-28s %14.1f %14.1f %9.1f%%%s\n', name, a, b, rel*100, flag);
    end
end
"""


README = """# MATLAB / Simulink bridge

The executable telemedicine model lives in Python
(`src/drscreen/sim/telemedicine.py`) because the rest of the pipeline is
Python and one source of truth beats two. This directory holds the Simulink
realisation required by the problem statement, generated from that same
configuration.

## Files

| file | purpose |
|---|---|
| `dr_screening_params.m` | every parameter as a MATLAB struct, generated from `SimConfig` |
| `build_dr_screening_model.m` | builds the SimEvents block diagram programmatically |
| `validate_against_simpy.m` | runs the Simulink model and diffs its outputs against the SimPy JSON |

## Regenerating

```
python scripts/run_simulation.py --export-matlab matlab/
```

Any change to `SimConfig` flows into `dr_screening_params.m`, so the two
runtimes cannot silently drift apart.

## Two things the generated script does not build

`build_dr_screening_model.m` lays out the forward topology. Two elements need
the graphical editor (or hand-written `add_line` calls against specific port
indices) and are present in the shipped `.slx`:

1. **The recapture feedback path** — `QualityGate` port 2 routes back into
   `CameraQueue`, carrying an attempt-count attribute that a second switch
   uses to give up after `max_recaptures`. This loop is the single most
   important non-obvious behaviour in the model: tightening the quality gate
   costs camera throughput super-linearly, because rejected patients re-enter
   the queue they just left.

2. **The link-state Markov chain** — a two-state chain (up/down) with mean
   sojourn times `net_uptime_mean_min` and `net_outage_mean_min` driving the
   `LinkAvailable` entity gate.

## Which model should I trust?

The SimPy model, because it is the one under test — it runs in CI, it is
what the optimiser searches, and its outputs are what the validation report
quotes. The Simulink model exists so the work can be inspected and extended
inside MATLAB, and `validate_against_simpy.m` is what keeps it honest.
"""


def export_all(cfg: SimConfig, out_dir: str | Path) -> dict[str, Path]:
    d = Path(out_dir)
    d.mkdir(parents=True, exist_ok=True)
    paths = {
        "params": emit_params(cfg, d / "dr_screening_params.m"),
        "build": d / "build_dr_screening_model.m",
        "validate": d / "validate_against_simpy.m",
        "readme": d / "README.md",
    }
    paths["build"].write_text(BUILD_SCRIPT, encoding="utf-8")
    paths["validate"].write_text(VALIDATION_SCRIPT, encoding="utf-8")
    paths["readme"].write_text(README, encoding="utf-8")
    return paths
