"""Real fundus photographs shipped with the repository.

These twelve images replace the generated phantoms the project used to lean on
for demos, benchmarks and tests. They are real retinas from the APTOS-2019 and
IDRiD held-out *test* splits -- never trained on, never validated on, never used
to fit a threshold -- and they are committed (about 2 MB total), so anything that
needs "a fundus image" has one without a 10 GB download and without drawing a
picture of a retina and calling it one.

The distinction is not cosmetic. A phantom is generated by the same project that
grades it, which makes any result measured on one circular; and a detector tuned
against drawn lesions learns the drawing, not the disease. Several real defects
in this codebase were invisible to the phantom set for exactly that reason --
the FOV gate rejected a third of genuinely gradeable real images because
phantoms always render a black margin, and the triage rule escalated every real
photograph to urgent because phantoms never exercised an unsupervised channel.

Grades come from each corpus's own reference standard, carried through
``outputs/verification_set/verification_summary.json``.
"""
from __future__ import annotations

from functools import lru_cache
from pathlib import Path

import cv2
import numpy as np

#: Repository root, resolved from this file rather than the working directory.
_ROOT = Path(__file__).resolve().parents[3]

SAMPLE_DIR = _ROOT / "outputs" / "verification_set" / "images"
SUMMARY = _ROOT / "outputs" / "verification_set" / "verification_summary.json"

#: case name -> ICDR grade from the source corpus's reference standard.
#: Mirrors the filenames, which encode the grade, so a mismatch is visible.
SAMPLE_GRADES: dict[str, int] = {
    "grade0_case1": 0, "grade0_case2": 0, "grade0_case3": 0,
    "grade1_case1": 1, "grade1_case2": 1, "grade1_case3": 1,
    "grade2_case1": 2, "grade2_case2": 2,
    "grade3_case1": 3, "grade3_case2": 3,
    "grade4_case1": 4, "grade4_case2": 4,
}


class NoSampleImages(FileNotFoundError):
    """Raised when the committed sample photographs are missing."""


@lru_cache(maxsize=1)
def sample_paths() -> tuple[Path, ...]:
    """Every committed sample photograph, in stable name order."""
    if not SAMPLE_DIR.is_dir():
        return ()
    return tuple(sorted(p for p in SAMPLE_DIR.iterdir()
                        if p.suffix.lower() in (".jpg", ".jpeg", ".png")))


def available() -> bool:
    return bool(sample_paths())


def _require(paths: tuple[Path, ...]) -> tuple[Path, ...]:
    if not paths:
        raise NoSampleImages(
            f"No sample photographs under {SAMPLE_DIR}. They are committed to "
            "the repository; rebuild them with scripts/build_verification_set.py "
            "if they have been deleted.")
    return paths


def paths_for_grade(grade: int) -> tuple[Path, ...]:
    """Sample paths whose reference grade is ``grade``."""
    want = {n for n, g in SAMPLE_GRADES.items() if g == int(grade)}
    return tuple(p for p in sample_paths() if p.stem in want)


def load(name_or_path: str | Path | None = None, grade: int | None = None,
         size: int | None = None) -> tuple[np.ndarray, str, int | None]:
    """Load one sample as BGR uint8.

    Returns ``(image, name, reference_grade)``. With no arguments it returns the
    first sample; ``grade`` picks one of that severity; ``name_or_path`` takes a
    case name (``"grade3_case1"``) or an explicit path.
    """
    if isinstance(name_or_path, (str, Path)) and Path(name_or_path).is_file():
        p = Path(name_or_path)
    elif name_or_path is not None:
        stem = str(name_or_path)
        hits = [q for q in _require(sample_paths()) if q.stem == stem]
        if not hits:
            raise NoSampleImages(f"No sample named {stem!r} in {SAMPLE_DIR}")
        p = hits[0]
    elif grade is not None:
        hits = paths_for_grade(grade)
        if not hits:
            raise NoSampleImages(f"No sample photograph of grade {grade}")
        p = hits[0]
    else:
        p = _require(sample_paths())[0]

    img = cv2.imread(str(p), cv2.IMREAD_COLOR)
    if img is None:
        raise NoSampleImages(f"Cannot read {p}")
    if size is not None and max(img.shape[:2]) != size:
        h, w = img.shape[:2]
        sc = size / max(h, w)
        img = cv2.resize(img, (max(1, int(round(w * sc))), max(1, int(round(h * sc)))),
                         interpolation=cv2.INTER_AREA if sc < 1 else cv2.INTER_LINEAR)
    return img, p.stem, SAMPLE_GRADES.get(p.stem)


def load_all(size: int | None = None) -> list[tuple[np.ndarray, str, int | None]]:
    return [load(p, size=size) for p in _require(sample_paths())]
