% STARTUP  Put the MATLAB screening codebase on the path.
%
% MATLAB runs this automatically when it starts with convrt_matlab as the
% current folder; run it by hand otherwise. The launchers (launch_console,
% launch_web, run_demo, run_tests) add what they need themselves, so this is
% a convenience, not a requirement.

% (MATLAB Compiler bundles startup.m into apps; the paths below exist only in
% the source tree, so the compiled app skips it.)
if ~isdeployed
    drscreenRoot = fileparts(mfilename('fullpath'));
    addpath(drscreenRoot, fullfile(drscreenRoot, 'app'), fullfile(drscreenRoot, 'tests'), ...
            fullfile(drscreenRoot, 'simulation'), fullfile(drscreenRoot, 'deploy'));
    fprintf(['DR screening (MATLAB) ready.\n' ...
             '  launch_console          desktop screening console\n' ...
             '  launch_web              web console + REST API at http://127.0.0.1:8000\n' ...
             '  run_demo                screen images from the command line\n' ...
             '  run_validation          metrics on the committed real photographs\n' ...
             '  run_tests               parity tests against the Python pipeline\n' ...
             '  check_install           which toolboxes are present\n']);
    clear drscreenRoot
end
