/* Generated by scripts/build_web_casedata.py - do not edit by hand. */
window.DR_CASES = {
 "generated": "scripts/build_web_casedata.py",
 "note": "Recorded output of a real pipeline run over the committed held-out photographs. The page replays it; it does not infer.",
 "gradeLabels": [
  "No apparent DR",
  "Mild NPDR",
  "Moderate NPDR",
  "Severe NPDR",
  "Proliferative DR"
 ],
 "cases": [
  {
   "id": "grade0_case1",
   "image": "../outputs/verification_set/images/grade0_case1.jpg",
   "panel": "../outputs/verification_set/reports/grade0_case1_panel.png",
   "report": "../outputs/verification_set/reports/grade0_case1_report.html",
   "source": "APTOS-2019",
   "px": [
    1050,
    1050
   ],
   "trueGrade": 0,
   "grade": 0,
   "gradeLabel": "No apparent DR",
   "classProbs": [
    0.988,
    0.0068,
    0.0043,
    0.0005,
    0.0004
   ],
   "referable": false,
   "referableP": 0.0,
   "sightThreatP": 0.0009,
   "confidence": 0.988,
   "entropy": 0.0761,
   "epistemic": 6e-05,
   "decision": "auto_report",
   "urgency": "routine",
   "dmeRisk": 2,
   "quality": {
    "overall": "good",
    "gradeable": true,
    "confidence": 0.8667,
    "scores": {
     "focus": 0.7523,
     "illumination": 0.7307,
     "contrast": 0.944,
     "fov": 0.9994,
     "macula": 0.8367,
     "artifact": 1.0,
     "under_exposure": 0.9987,
     "over_exposure": 1.0,
     "noise": 1.0
    },
    "verdicts": {
     "focus": "pass",
     "illumination": "pass",
     "contrast": "pass",
     "fov": "pass",
     "macula": "pass",
     "artifact": "pass",
     "under_exposure": "pass",
     "over_exposure": "pass",
     "noise": "pass"
    },
    "issues": [],
    "advice": []
   },
   "enhancement": [
    "grey_world"
   ],
   "landmarks": {
    "discConf": 1.0,
    "foveaConf": 0.6372,
    "laterality": "OD",
    "discDiameterPx": 94.3
   },
   "counts": {
    "microaneurysm": 3,
    "hemorrhage": 4,
    "hard_exudate": 4,
    "soft_exudate": 0,
    "neovascularization": 1
   },
   "perQuadrant": {
    "microaneurysm": {
     "superior": 0,
     "inferior": 2,
     "nasal": 0,
     "temporal": 1
    },
    "hemorrhage": {
     "superior": 0,
     "inferior": 2,
     "nasal": 2,
     "temporal": 0
    },
    "hard_exudate": {
     "superior": 0,
     "inferior": 0,
     "nasal": 1,
     "temporal": 3
    },
    "soft_exudate": {
     "superior": 0,
     "inferior": 0,
     "nasal": 0,
     "temporal": 0
    },
    "neovascularization": {
     "superior": 1,
     "inferior": 0,
     "nasal": 0,
     "temporal": 0
    }
   },
   "nearestLesionDD": 0.38,
   "lesionsNearFovea": 2,
   "quadrantsWithHaem": 0,
   "ruleGrade": 2,
   "ruleReasons": [
    "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
    "More than microaneurysms alone but less than severe NPDR: 3 microaneurysms, 4 haemorrhages, 4 hard-exudate focus/foci."
   ],
   "agreement": "disagree",
   "recapture": [],
   "evidence": {
    "findings": [
     {
      "finding": "neovascularization",
      "status": "not assessed",
      "detail": "no pixel supervision for this class in the training corpus; absence of a detection is not evidence of absence of the lesion."
     },
     {
      "finding": "microaneurysm",
      "count": 3,
      "per_quadrant": {
       "inferior": 2,
       "temporal": 1
      },
      "area_percent": 0.009
     },
     {
      "finding": "hemorrhage",
      "count": 4,
      "per_quadrant": {
       "inferior": 2,
       "nasal": 2
      },
      "area_percent": 0.036
     },
     {
      "finding": "hard exudate",
      "count": 4,
      "per_quadrant": {
       "nasal": 1,
       "temporal": 3
      },
      "area_percent": 0.019
     }
    ],
    "criteria": [
     "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
     "More than microaneurysms alone but less than severe NPDR: 3 microaneurysms, 4 haemorrhages, 4 hard-exudate focus/foci."
    ],
    "macula": "1 hard-exudate focus/foci within 1 disc diameter of the fovea - clinically significant macular oedema likely; urgent referral."
   },
   "stages": [
    {
     "stage": "1",
     "key": "geometry",
     "ms": 129.8
    },
    {
     "stage": "2",
     "key": "quality",
     "ms": 27.6
    },
    {
     "stage": "3",
     "key": "enhancement",
     "ms": 22.3
    },
    {
     "stage": "3",
     "key": "quality_recheck",
     "ms": 37.0
    },
    {
     "stage": "4",
     "key": "landmarks",
     "ms": 95.2
    },
    {
     "stage": "5",
     "key": "segmentation",
     "ms": 461.2
    },
    {
     "stage": "6",
     "key": "clinical_features",
     "ms": 25.2
    },
    {
     "stage": "7b",
     "key": "grading",
     "ms": 388.6
    },
    {
     "stage": "9",
     "key": "explanation",
     "ms": 194.3
    }
   ],
   "totalMs": 1493.4,
   "modelVersion": "drscreen-1.0.0"
  },
  {
   "id": "grade0_case2",
   "image": "../outputs/verification_set/images/grade0_case2.jpg",
   "panel": "../outputs/verification_set/reports/grade0_case2_panel.png",
   "report": "../outputs/verification_set/reports/grade0_case2_report.html",
   "source": "APTOS-2019",
   "px": [
    1050,
    1050
   ],
   "trueGrade": 0,
   "grade": 0,
   "gradeLabel": "No apparent DR",
   "classProbs": [
    0.9864,
    0.0097,
    0.0032,
    0.0003,
    0.0004
   ],
   "referable": false,
   "referableP": 0.0,
   "sightThreatP": 0.0007,
   "confidence": 0.9864,
   "entropy": 0.0822,
   "epistemic": 6e-05,
   "decision": "auto_report",
   "urgency": "routine",
   "dmeRisk": 2,
   "quality": {
    "overall": "good",
    "gradeable": true,
    "confidence": 0.8371,
    "scores": {
     "focus": 0.776,
     "illumination": 0.6496,
     "contrast": 0.9453,
     "fov": 0.9995,
     "macula": 0.825,
     "artifact": 1.0,
     "under_exposure": 0.9982,
     "over_exposure": 1.0,
     "noise": 1.0
    },
    "verdicts": {
     "focus": "pass",
     "illumination": "pass",
     "contrast": "pass",
     "fov": "pass",
     "macula": "pass",
     "artifact": "pass",
     "under_exposure": "pass",
     "over_exposure": "pass",
     "noise": "pass"
    },
    "issues": [],
    "advice": []
   },
   "enhancement": [
    "grey_world"
   ],
   "landmarks": {
    "discConf": 1.0,
    "foveaConf": 0.6112,
    "laterality": "OD",
    "discDiameterPx": 107.1
   },
   "counts": {
    "microaneurysm": 1,
    "hemorrhage": 0,
    "hard_exudate": 4,
    "soft_exudate": 0,
    "neovascularization": 1
   },
   "perQuadrant": {
    "microaneurysm": {
     "superior": 0,
     "inferior": 0,
     "nasal": 0,
     "temporal": 1
    },
    "hemorrhage": {
     "superior": 0,
     "inferior": 0,
     "nasal": 0,
     "temporal": 0
    },
    "hard_exudate": {
     "superior": 0,
     "inferior": 2,
     "nasal": 2,
     "temporal": 0
    },
    "soft_exudate": {
     "superior": 0,
     "inferior": 0,
     "nasal": 0,
     "temporal": 0
    },
    "neovascularization": {
     "superior": 0,
     "inferior": 0,
     "nasal": 1,
     "temporal": 0
    }
   },
   "nearestLesionDD": 0.02,
   "lesionsNearFovea": 2,
   "quadrantsWithHaem": 0,
   "ruleGrade": 2,
   "ruleReasons": [
    "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
    "More than microaneurysms alone but less than severe NPDR: 1 microaneurysm, 4 hard-exudate focus/foci."
   ],
   "agreement": "disagree",
   "recapture": [],
   "evidence": {
    "findings": [
     {
      "finding": "neovascularization",
      "status": "not assessed",
      "detail": "no pixel supervision for this class in the training corpus; absence of a detection is not evidence of absence of the lesion."
     },
     {
      "finding": "microaneurysm",
      "count": 1,
      "per_quadrant": {
       "temporal": 1
      },
      "area_percent": 0.006
     },
     {
      "finding": "hard exudate",
      "count": 4,
      "per_quadrant": {
       "inferior": 2,
       "nasal": 2
      },
      "area_percent": 0.03
     }
    ],
    "criteria": [
     "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
     "More than microaneurysms alone but less than severe NPDR: 1 microaneurysm, 4 hard-exudate focus/foci."
    ],
    "macula": "1 hard-exudate focus/foci within 1 disc diameter of the fovea - clinically significant macular oedema likely; urgent referral."
   },
   "stages": [
    {
     "stage": "1",
     "key": "geometry",
     "ms": 151.4
    },
    {
     "stage": "2",
     "key": "quality",
     "ms": 35.4
    },
    {
     "stage": "3",
     "key": "enhancement",
     "ms": 22.7
    },
    {
     "stage": "3",
     "key": "quality_recheck",
     "ms": 30.0
    },
    {
     "stage": "4",
     "key": "landmarks",
     "ms": 78.8
    },
    {
     "stage": "5",
     "key": "segmentation",
     "ms": 140.3
    },
    {
     "stage": "6",
     "key": "clinical_features",
     "ms": 28.9
    },
    {
     "stage": "7b",
     "key": "grading",
     "ms": 108.8
    },
    {
     "stage": "9",
     "key": "explanation",
     "ms": 33.5
    }
   ],
   "totalMs": 656.2,
   "modelVersion": "drscreen-1.0.0"
  },
  {
   "id": "grade0_case3",
   "image": "../outputs/verification_set/images/grade0_case3.jpg",
   "panel": "../outputs/verification_set/reports/grade0_case3_panel.png",
   "report": "../outputs/verification_set/reports/grade0_case3_report.html",
   "source": "IDRiD",
   "px": [
    1280,
    850
   ],
   "trueGrade": 0,
   "grade": 0,
   "gradeLabel": "No apparent DR",
   "classProbs": [
    0.9237,
    0.0229,
    0.0445,
    0.0036,
    0.0053
   ],
   "referable": false,
   "referableP": 0.0238,
   "sightThreatP": 0.0089,
   "confidence": 0.9237,
   "entropy": 0.3464,
   "epistemic": 0.00066,
   "decision": "auto_report",
   "urgency": "routine",
   "dmeRisk": 1,
   "quality": {
    "overall": "good",
    "gradeable": true,
    "confidence": 0.8057,
    "scores": {
     "focus": 0.8066,
     "illumination": 0.9006,
     "contrast": 0.9307,
     "fov": 0.9444,
     "macula": 1.0,
     "artifact": 1.0,
     "under_exposure": 0.5818,
     "over_exposure": 1.0,
     "noise": 1.0
    },
    "verdicts": {
     "focus": "pass",
     "illumination": "pass",
     "contrast": "pass",
     "fov": "pass",
     "macula": "pass",
     "artifact": "pass",
     "under_exposure": "pass",
     "over_exposure": "pass",
     "noise": "pass"
    },
    "issues": [],
    "advice": []
   },
   "enhancement": [
    "grey_world",
    "illumination_normalize"
   ],
   "landmarks": {
    "discConf": 1.0,
    "foveaConf": 1.0,
    "laterality": "OS",
    "discDiameterPx": 79.2
   },
   "counts": {
    "microaneurysm": 3,
    "hemorrhage": 4,
    "hard_exudate": 1,
    "soft_exudate": 0,
    "neovascularization": 1
   },
   "perQuadrant": {
    "microaneurysm": {
     "superior": 0,
     "inferior": 2,
     "nasal": 0,
     "temporal": 1
    },
    "hemorrhage": {
     "superior": 1,
     "inferior": 0,
     "nasal": 0,
     "temporal": 3
    },
    "hard_exudate": {
     "superior": 0,
     "inferior": 0,
     "nasal": 1,
     "temporal": 0
    },
    "soft_exudate": {
     "superior": 0,
     "inferior": 0,
     "nasal": 0,
     "temporal": 0
    },
    "neovascularization": {
     "superior": 0,
     "inferior": 0,
     "nasal": 1,
     "temporal": 0
    }
   },
   "nearestLesionDD": 0.92,
   "lesionsNearFovea": 1,
   "quadrantsWithHaem": 0,
   "ruleGrade": 2,
   "ruleReasons": [
    "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
    "More than microaneurysms alone but less than severe NPDR: 3 microaneurysms, 4 haemorrhages, 1 hard-exudate focus/foci."
   ],
   "agreement": "disagree",
   "recapture": [],
   "evidence": {
    "findings": [
     {
      "finding": "neovascularization",
      "status": "not assessed",
      "detail": "no pixel supervision for this class in the training corpus; absence of a detection is not evidence of absence of the lesion."
     },
     {
      "finding": "microaneurysm",
      "count": 3,
      "per_quadrant": {
       "inferior": 2,
       "temporal": 1
      },
      "area_percent": 0.008
     },
     {
      "finding": "hemorrhage",
      "count": 4,
      "per_quadrant": {
       "superior": 1,
       "temporal": 3
      },
      "area_percent": 0.104
     },
     {
      "finding": "hard exudate",
      "count": 1,
      "per_quadrant": {
       "nasal": 1
      },
      "area_percent": 0.009
     }
    ],
    "criteria": [
     "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
     "More than microaneurysms alone but less than severe NPDR: 3 microaneurysms, 4 haemorrhages, 1 hard-exudate focus/foci."
    ],
    "macula": "Hard exudates present but the nearest is 0.9 DD from the fovea."
   },
   "stages": [
    {
     "stage": "1",
     "key": "geometry",
     "ms": 136.5
    },
    {
     "stage": "2",
     "key": "quality",
     "ms": 29.7
    },
    {
     "stage": "3",
     "key": "enhancement",
     "ms": 96.0
    },
    {
     "stage": "3",
     "key": "quality_recheck",
     "ms": 36.7
    },
    {
     "stage": "4",
     "key": "landmarks",
     "ms": 58.5
    },
    {
     "stage": "5",
     "key": "segmentation",
     "ms": 124.5
    },
    {
     "stage": "6",
     "key": "clinical_features",
     "ms": 27.8
    },
    {
     "stage": "7b",
     "key": "grading",
     "ms": 89.3
    },
    {
     "stage": "9",
     "key": "explanation",
     "ms": 34.3
    }
   ],
   "totalMs": 670.3,
   "modelVersion": "drscreen-1.0.0"
  },
  {
   "id": "grade1_case1",
   "image": "../outputs/verification_set/images/grade1_case1.jpg",
   "panel": "../outputs/verification_set/reports/grade1_case1_panel.png",
   "report": "../outputs/verification_set/reports/grade1_case1_report.html",
   "source": "APTOS-2019",
   "px": [
    1280,
    920
   ],
   "trueGrade": 1,
   "grade": 1,
   "gradeLabel": "Mild NPDR",
   "classProbs": [
    0.023,
    0.9426,
    0.0326,
    0.0004,
    0.0014
   ],
   "referable": false,
   "referableP": 0.0238,
   "sightThreatP": 0.0018,
   "confidence": 0.9426,
   "entropy": 0.2663,
   "epistemic": 0.00019,
   "decision": "auto_report",
   "urgency": "routine",
   "dmeRisk": 2,
   "quality": {
    "overall": "good",
    "gradeable": true,
    "confidence": 0.7708,
    "scores": {
     "focus": 0.6671,
     "illumination": 0.672,
     "contrast": 0.9255,
     "fov": 0.9131,
     "macula": 0.6376,
     "artifact": 1.0,
     "under_exposure": 0.8545,
     "over_exposure": 1.0,
     "noise": 1.0
    },
    "verdicts": {
     "focus": "pass",
     "illumination": "pass",
     "contrast": "pass",
     "fov": "pass",
     "macula": "pass",
     "artifact": "pass",
     "under_exposure": "pass",
     "over_exposure": "pass",
     "noise": "pass"
    },
    "issues": [],
    "advice": []
   },
   "enhancement": [
    "grey_world"
   ],
   "landmarks": {
    "discConf": 1.0,
    "foveaConf": 0.1947,
    "laterality": "OS",
    "discDiameterPx": 64.3
   },
   "counts": {
    "microaneurysm": 6,
    "hemorrhage": 3,
    "hard_exudate": 13,
    "soft_exudate": 0,
    "neovascularization": 1
   },
   "perQuadrant": {
    "microaneurysm": {
     "superior": 1,
     "inferior": 2,
     "nasal": 2,
     "temporal": 1
    },
    "hemorrhage": {
     "superior": 2,
     "inferior": 1,
     "nasal": 0,
     "temporal": 0
    },
    "hard_exudate": {
     "superior": 1,
     "inferior": 5,
     "nasal": 7,
     "temporal": 0
    },
    "soft_exudate": {
     "superior": 0,
     "inferior": 0,
     "nasal": 0,
     "temporal": 0
    },
    "neovascularization": {
     "superior": 0,
     "inferior": 1,
     "nasal": 0,
     "temporal": 0
    }
   },
   "nearestLesionDD": 0.25,
   "lesionsNearFovea": 8,
   "quadrantsWithHaem": 0,
   "ruleGrade": 2,
   "ruleReasons": [
    "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
    "More than microaneurysms alone but less than severe NPDR: 6 microaneurysms, 3 haemorrhages, 13 hard-exudate focus/foci."
   ],
   "agreement": "within_one_grade",
   "recapture": [],
   "evidence": {
    "findings": [
     {
      "finding": "neovascularization",
      "status": "not assessed",
      "detail": "no pixel supervision for this class in the training corpus; absence of a detection is not evidence of absence of the lesion."
     },
     {
      "finding": "microaneurysm",
      "count": 6,
      "per_quadrant": {
       "superior": 1,
       "inferior": 2,
       "nasal": 2,
       "temporal": 1
      },
      "area_percent": 0.046
     },
     {
      "finding": "hemorrhage",
      "count": 3,
      "per_quadrant": {
       "superior": 2,
       "inferior": 1
      },
      "area_percent": 0.053
     },
     {
      "finding": "hard exudate",
      "count": 13,
      "per_quadrant": {
       "superior": 1,
       "inferior": 5,
       "nasal": 7
      },
      "area_percent": 0.213
     }
    ],
    "criteria": [
     "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
     "More than microaneurysms alone but less than severe NPDR: 6 microaneurysms, 3 haemorrhages, 13 hard-exudate focus/foci."
    ],
    "macula": "2 hard-exudate focus/foci within 1 disc diameter of the fovea - clinically significant macular oedema likely; urgent referral."
   },
   "stages": [
    {
     "stage": "1",
     "key": "geometry",
     "ms": 108.4
    },
    {
     "stage": "2",
     "key": "quality",
     "ms": 30.5
    },
    {
     "stage": "3",
     "key": "enhancement",
     "ms": 16.4
    },
    {
     "stage": "3",
     "key": "quality_recheck",
     "ms": 26.9
    },
    {
     "stage": "4",
     "key": "landmarks",
     "ms": 49.9
    },
    {
     "stage": "5",
     "key": "segmentation",
     "ms": 114.3
    },
    {
     "stage": "6",
     "key": "clinical_features",
     "ms": 23.8
    },
    {
     "stage": "7b",
     "key": "grading",
     "ms": 79.5
    },
    {
     "stage": "9",
     "key": "explanation",
     "ms": 32.7
    }
   ],
   "totalMs": 502.9,
   "modelVersion": "drscreen-1.0.0"
  },
  {
   "id": "grade1_case2",
   "image": "../outputs/verification_set/images/grade1_case2.jpg",
   "panel": "../outputs/verification_set/reports/grade1_case2_panel.png",
   "report": "../outputs/verification_set/reports/grade1_case2_report.html",
   "source": "APTOS-2019",
   "px": [
    1280,
    920
   ],
   "trueGrade": 1,
   "grade": 1,
   "gradeLabel": "Mild NPDR",
   "classProbs": [
    0.022,
    0.9161,
    0.0592,
    0.0009,
    0.0018
   ],
   "referable": false,
   "referableP": 0.0238,
   "sightThreatP": 0.0027,
   "confidence": 0.9161,
   "entropy": 0.3494,
   "epistemic": 0.00106,
   "decision": "auto_report",
   "urgency": "routine",
   "dmeRisk": 2,
   "quality": {
    "overall": "good",
    "gradeable": true,
    "confidence": 0.8091,
    "scores": {
     "focus": 0.6938,
     "illumination": 0.7127,
     "contrast": 0.9911,
     "fov": 0.913,
     "macula": 0.7181,
     "artifact": 1.0,
     "under_exposure": 0.8182,
     "over_exposure": 1.0,
     "noise": 1.0
    },
    "verdicts": {
     "focus": "pass",
     "illumination": "pass",
     "contrast": "pass",
     "fov": "pass",
     "macula": "pass",
     "artifact": "pass",
     "under_exposure": "pass",
     "over_exposure": "pass",
     "noise": "pass"
    },
    "issues": [],
    "advice": []
   },
   "enhancement": [
    "grey_world"
   ],
   "landmarks": {
    "discConf": 1.0,
    "foveaConf": 0.3736,
    "laterality": "OS",
    "discDiameterPx": 72.0
   },
   "counts": {
    "microaneurysm": 9,
    "hemorrhage": 1,
    "hard_exudate": 11,
    "soft_exudate": 1,
    "neovascularization": 1
   },
   "perQuadrant": {
    "microaneurysm": {
     "superior": 1,
     "inferior": 4,
     "nasal": 2,
     "temporal": 2
    },
    "hemorrhage": {
     "superior": 1,
     "inferior": 0,
     "nasal": 0,
     "temporal": 0
    },
    "hard_exudate": {
     "superior": 3,
     "inferior": 4,
     "nasal": 1,
     "temporal": 3
    },
    "soft_exudate": {
     "superior": 1,
     "inferior": 0,
     "nasal": 0,
     "temporal": 0
    },
    "neovascularization": {
     "superior": 1,
     "inferior": 0,
     "nasal": 0,
     "temporal": 0
    }
   },
   "nearestLesionDD": 0.11,
   "lesionsNearFovea": 11,
   "quadrantsWithHaem": 0,
   "ruleGrade": 2,
   "ruleReasons": [
    "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
    "More than microaneurysms alone but less than severe NPDR: 9 microaneurysms, 1 haemorrhage, 11 hard-exudate focus/foci, 1 cotton-wool spot."
   ],
   "agreement": "within_one_grade",
   "recapture": [],
   "evidence": {
    "findings": [
     {
      "finding": "neovascularization",
      "status": "not assessed",
      "detail": "no pixel supervision for this class in the training corpus; absence of a detection is not evidence of absence of the lesion."
     },
     {
      "finding": "microaneurysm",
      "count": 9,
      "per_quadrant": {
       "superior": 1,
       "inferior": 4,
       "nasal": 2,
       "temporal": 2
      },
      "area_percent": 0.048
     },
     {
      "finding": "hemorrhage",
      "count": 1,
      "per_quadrant": {
       "superior": 1
      },
      "area_percent": 0.056
     },
     {
      "finding": "hard exudate",
      "count": 11,
      "per_quadrant": {
       "superior": 3,
       "inferior": 4,
       "nasal": 1,
       "temporal": 3
      },
      "area_percent": 0.144
     },
     {
      "finding": "soft exudate",
      "count": 1,
      "per_quadrant": {
       "superior": 1
      },
      "area_percent": 0.061
     }
    ],
    "criteria": [
     "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
     "More than microaneurysms alone but less than severe NPDR: 9 microaneurysms, 1 haemorrhage, 11 hard-exudate focus/foci, 1 cotton-wool spot."
    ],
    "macula": "7 hard-exudate focus/foci within 1 disc diameter of the fovea - clinically significant macular oedema likely; urgent referral."
   },
   "stages": [
    {
     "stage": "1",
     "key": "geometry",
     "ms": 157.7
    },
    {
     "stage": "2",
     "key": "quality",
     "ms": 38.1
    },
    {
     "stage": "3",
     "key": "enhancement",
     "ms": 20.9
    },
    {
     "stage": "3",
     "key": "quality_recheck",
     "ms": 33.5
    },
    {
     "stage": "4",
     "key": "landmarks",
     "ms": 67.0
    },
    {
     "stage": "5",
     "key": "segmentation",
     "ms": 128.7
    },
    {
     "stage": "6",
     "key": "clinical_features",
     "ms": 34.0
    },
    {
     "stage": "7b",
     "key": "grading",
     "ms": 106.9
    },
    {
     "stage": "9",
     "key": "explanation",
     "ms": 36.1
    }
   ],
   "totalMs": 656.3,
   "modelVersion": "drscreen-1.0.0"
  },
  {
   "id": "grade1_case3",
   "image": "../outputs/verification_set/images/grade1_case3.jpg",
   "panel": "../outputs/verification_set/reports/grade1_case3_panel.png",
   "report": "../outputs/verification_set/reports/grade1_case3_report.html",
   "source": "APTOS-2019",
   "px": [
    1280,
    920
   ],
   "trueGrade": 1,
   "grade": 1,
   "gradeLabel": "Mild NPDR",
   "classProbs": [
    0.0626,
    0.8891,
    0.0291,
    0.0063,
    0.013
   ],
   "referable": false,
   "referableP": 0.0238,
   "sightThreatP": 0.0193,
   "confidence": 0.8891,
   "entropy": 0.4691,
   "epistemic": 0.00142,
   "decision": "auto_report",
   "urgency": "routine",
   "dmeRisk": 1,
   "quality": {
    "overall": "good",
    "gradeable": true,
    "confidence": 0.7742,
    "scores": {
     "focus": 0.5676,
     "illumination": 0.8601,
     "contrast": 0.9949,
     "fov": 0.913,
     "macula": 0.6805,
     "artifact": 1.0,
     "under_exposure": 1.0,
     "over_exposure": 1.0,
     "noise": 1.0
    },
    "verdicts": {
     "focus": "pass",
     "illumination": "pass",
     "contrast": "pass",
     "fov": "pass",
     "macula": "pass",
     "artifact": "pass",
     "under_exposure": "pass",
     "over_exposure": "pass",
     "noise": "pass"
    },
    "issues": [],
    "advice": []
   },
   "enhancement": [
    "grey_world"
   ],
   "landmarks": {
    "discConf": 1.0,
    "foveaConf": 0.29,
    "laterality": "OS",
    "discDiameterPx": 59.0
   },
   "counts": {
    "microaneurysm": 7,
    "hemorrhage": 2,
    "hard_exudate": 11,
    "soft_exudate": 0,
    "neovascularization": 1
   },
   "perQuadrant": {
    "microaneurysm": {
     "superior": 0,
     "inferior": 5,
     "nasal": 0,
     "temporal": 2
    },
    "hemorrhage": {
     "superior": 1,
     "inferior": 0,
     "nasal": 0,
     "temporal": 1
    },
    "hard_exudate": {
     "superior": 1,
     "inferior": 3,
     "nasal": 1,
     "temporal": 6
    },
    "soft_exudate": {
     "superior": 0,
     "inferior": 0,
     "nasal": 0,
     "temporal": 0
    },
    "neovascularization": {
     "superior": 0,
     "inferior": 1,
     "nasal": 0,
     "temporal": 0
    }
   },
   "nearestLesionDD": 0.52,
   "lesionsNearFovea": 1,
   "quadrantsWithHaem": 0,
   "ruleGrade": 2,
   "ruleReasons": [
    "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
    "More than microaneurysms alone but less than severe NPDR: 7 microaneurysms, 2 haemorrhages, 11 hard-exudate focus/foci."
   ],
   "agreement": "within_one_grade",
   "recapture": [],
   "evidence": {
    "findings": [
     {
      "finding": "neovascularization",
      "status": "not assessed",
      "detail": "no pixel supervision for this class in the training corpus; absence of a detection is not evidence of absence of the lesion."
     },
     {
      "finding": "microaneurysm",
      "count": 7,
      "per_quadrant": {
       "inferior": 5,
       "temporal": 2
      },
      "area_percent": 0.024
     },
     {
      "finding": "hemorrhage",
      "count": 2,
      "per_quadrant": {
       "superior": 1,
       "temporal": 1
      },
      "area_percent": 0.053
     },
     {
      "finding": "hard exudate",
      "count": 11,
      "per_quadrant": {
       "superior": 1,
       "inferior": 3,
       "nasal": 1,
       "temporal": 6
      },
      "area_percent": 0.354
     }
    ],
    "criteria": [
     "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
     "More than microaneurysms alone but less than severe NPDR: 7 microaneurysms, 2 haemorrhages, 11 hard-exudate focus/foci."
    ],
    "macula": "Hard exudates present but the nearest is 0.5 DD from the fovea."
   },
   "stages": [
    {
     "stage": "1",
     "key": "geometry",
     "ms": 106.0
    },
    {
     "stage": "2",
     "key": "quality",
     "ms": 30.6
    },
    {
     "stage": "3",
     "key": "enhancement",
     "ms": 15.8
    },
    {
     "stage": "3",
     "key": "quality_recheck",
     "ms": 27.7
    },
    {
     "stage": "4",
     "key": "landmarks",
     "ms": 49.1
    },
    {
     "stage": "5",
     "key": "segmentation",
     "ms": 102.9
    },
    {
     "stage": "6",
     "key": "clinical_features",
     "ms": 18.7
    },
    {
     "stage": "7b",
     "key": "grading",
     "ms": 63.5
    },
    {
     "stage": "9",
     "key": "explanation",
     "ms": 30.9
    }
   ],
   "totalMs": 465.2,
   "modelVersion": "drscreen-1.0.0"
  },
  {
   "id": "grade2_case1",
   "image": "../outputs/verification_set/images/grade2_case1.jpg",
   "panel": "../outputs/verification_set/reports/grade2_case1_panel.png",
   "report": "../outputs/verification_set/reports/grade2_case1_report.html",
   "source": "APTOS-2019",
   "px": [
    1280,
    850
   ],
   "trueGrade": 2,
   "grade": 2,
   "gradeLabel": "Moderate NPDR",
   "classProbs": [
    0.0099,
    0.06,
    0.8071,
    0.0895,
    0.0335
   ],
   "referable": true,
   "referableP": 0.8824,
   "sightThreatP": 0.1229,
   "confidence": 0.8071,
   "entropy": 0.7172,
   "epistemic": 0.00245,
   "decision": "refer",
   "urgency": "urgent",
   "dmeRisk": 2,
   "quality": {
    "overall": "borderline",
    "gradeable": true,
    "confidence": 0.7281,
    "scores": {
     "focus": 0.4928,
     "illumination": 0.72,
     "contrast": 0.9422,
     "fov": 0.9225,
     "macula": 0.8579,
     "artifact": 1.0,
     "under_exposure": 1.0,
     "over_exposure": 1.0,
     "noise": 0.8896
    },
    "verdicts": {
     "focus": "borderline",
     "illumination": "pass",
     "contrast": "pass",
     "fov": "pass",
     "macula": "pass",
     "artifact": "pass",
     "under_exposure": "pass",
     "over_exposure": "pass",
     "noise": "pass"
    },
    "issues": [
     "focus"
    ],
    "advice": []
   },
   "enhancement": [
    "grey_world",
    "clahe_lab"
   ],
   "landmarks": {
    "discConf": 1.0,
    "foveaConf": 0.6842,
    "laterality": "OD",
    "discDiameterPx": 63.3
   },
   "counts": {
    "microaneurysm": 48,
    "hemorrhage": 46,
    "hard_exudate": 122,
    "soft_exudate": 0,
    "neovascularization": 1
   },
   "perQuadrant": {
    "microaneurysm": {
     "superior": 25,
     "inferior": 1,
     "nasal": 12,
     "temporal": 10
    },
    "hemorrhage": {
     "superior": 20,
     "inferior": 2,
     "nasal": 14,
     "temporal": 10
    },
    "hard_exudate": {
     "superior": 36,
     "inferior": 6,
     "nasal": 30,
     "temporal": 50
    },
    "soft_exudate": {
     "superior": 0,
     "inferior": 0,
     "nasal": 0,
     "temporal": 0
    },
    "neovascularization": {
     "superior": 1,
     "inferior": 0,
     "nasal": 0,
     "temporal": 0
    }
   },
   "nearestLesionDD": 0.22,
   "lesionsNearFovea": 20,
   "quadrantsWithHaem": 3,
   "ruleGrade": 2,
   "ruleReasons": [
    "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
    "More than microaneurysms alone but less than severe NPDR: 48 microaneurysms, 46 haemorrhages, 122 hard-exudate focus/foci."
   ],
   "agreement": "exact",
   "recapture": [],
   "evidence": {
    "findings": [
     {
      "finding": "neovascularization",
      "status": "not assessed",
      "detail": "no pixel supervision for this class in the training corpus; absence of a detection is not evidence of absence of the lesion."
     },
     {
      "finding": "microaneurysm",
      "count": 48,
      "per_quadrant": {
       "superior": 25,
       "inferior": 1,
       "nasal": 12,
       "temporal": 10
      },
      "area_percent": 0.23
     },
     {
      "finding": "hemorrhage",
      "count": 46,
      "per_quadrant": {
       "superior": 20,
       "inferior": 2,
       "nasal": 14,
       "temporal": 10
      },
      "area_percent": 2.751
     },
     {
      "finding": "hard exudate",
      "count": 122,
      "per_quadrant": {
       "superior": 36,
       "inferior": 6,
       "nasal": 30,
       "temporal": 50
      },
      "area_percent": 1.778
     }
    ],
    "criteria": [
     "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
     "More than microaneurysms alone but less than severe NPDR: 48 microaneurysms, 46 haemorrhages, 122 hard-exudate focus/foci."
    ],
    "macula": "18 hard-exudate focus/foci within 1 disc diameter of the fovea - clinically significant macular oedema likely; urgent referral."
   },
   "stages": [
    {
     "stage": "1",
     "key": "geometry",
     "ms": 150.3
    },
    {
     "stage": "2",
     "key": "quality",
     "ms": 36.2
    },
    {
     "stage": "3",
     "key": "enhancement",
     "ms": 21.4
    },
    {
     "stage": "3",
     "key": "quality_recheck",
     "ms": 37.4
    },
    {
     "stage": "4",
     "key": "landmarks",
     "ms": 62.5
    },
    {
     "stage": "5",
     "key": "segmentation",
     "ms": 131.1
    },
    {
     "stage": "6",
     "key": "clinical_features",
     "ms": 51.8
    },
    {
     "stage": "7b",
     "key": "grading",
     "ms": 95.0
    },
    {
     "stage": "9",
     "key": "explanation",
     "ms": 33.7
    }
   ],
   "totalMs": 644.9,
   "modelVersion": "drscreen-1.0.0"
  },
  {
   "id": "grade2_case2",
   "image": "../outputs/verification_set/images/grade2_case2.jpg",
   "panel": "../outputs/verification_set/reports/grade2_case2_panel.png",
   "report": "../outputs/verification_set/reports/grade2_case2_report.html",
   "source": "IDRiD",
   "px": [
    1280,
    850
   ],
   "trueGrade": 2,
   "grade": 2,
   "gradeLabel": "Moderate NPDR",
   "classProbs": [
    0.0391,
    0.0276,
    0.7157,
    0.1186,
    0.099
   ],
   "referable": true,
   "referableP": 0.8824,
   "sightThreatP": 0.2176,
   "confidence": 0.7157,
   "entropy": 0.9471,
   "epistemic": 0.00538,
   "decision": "refer",
   "urgency": "urgent",
   "dmeRisk": 2,
   "quality": {
    "overall": "good",
    "gradeable": true,
    "confidence": 0.8195,
    "scores": {
     "focus": 0.6856,
     "illumination": 0.8097,
     "contrast": 0.8367,
     "fov": 0.9442,
     "macula": 1.0,
     "artifact": 1.0,
     "under_exposure": 1.0,
     "over_exposure": 1.0,
     "noise": 0.6903
    },
    "verdicts": {
     "focus": "pass",
     "illumination": "pass",
     "contrast": "pass",
     "fov": "pass",
     "macula": "pass",
     "artifact": "pass",
     "under_exposure": "pass",
     "over_exposure": "pass",
     "noise": "pass"
    },
    "issues": [],
    "advice": []
   },
   "enhancement": [
    "grey_world",
    "illumination_normalize",
    "clahe_lab"
   ],
   "landmarks": {
    "discConf": 1.0,
    "foveaConf": 1.0,
    "laterality": "OD",
    "discDiameterPx": 88.2
   },
   "counts": {
    "microaneurysm": 33,
    "hemorrhage": 48,
    "hard_exudate": 86,
    "soft_exudate": 9,
    "neovascularization": 2
   },
   "perQuadrant": {
    "microaneurysm": {
     "superior": 6,
     "inferior": 5,
     "nasal": 8,
     "temporal": 14
    },
    "hemorrhage": {
     "superior": 14,
     "inferior": 5,
     "nasal": 16,
     "temporal": 13
    },
    "hard_exudate": {
     "superior": 50,
     "inferior": 3,
     "nasal": 11,
     "temporal": 22
    },
    "soft_exudate": {
     "superior": 1,
     "inferior": 1,
     "nasal": 7,
     "temporal": 0
    },
    "neovascularization": {
     "superior": 0,
     "inferior": 0,
     "nasal": 2,
     "temporal": 0
    }
   },
   "nearestLesionDD": 0.24,
   "lesionsNearFovea": 35,
   "quadrantsWithHaem": 3,
   "ruleGrade": 2,
   "ruleReasons": [
    "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
    "More than microaneurysms alone but less than severe NPDR: 33 microaneurysms, 48 haemorrhages, 86 hard-exudate focus/foci, 9 cotton-wool spots."
   ],
   "agreement": "exact",
   "recapture": [],
   "evidence": {
    "findings": [
     {
      "finding": "neovascularization",
      "status": "not assessed",
      "detail": "no pixel supervision for this class in the training corpus; absence of a detection is not evidence of absence of the lesion."
     },
     {
      "finding": "microaneurysm",
      "count": 33,
      "per_quadrant": {
       "superior": 6,
       "inferior": 5,
       "nasal": 8,
       "temporal": 14
      },
      "area_percent": 0.141
     },
     {
      "finding": "hemorrhage",
      "count": 48,
      "per_quadrant": {
       "superior": 14,
       "inferior": 5,
       "nasal": 16,
       "temporal": 13
      },
      "area_percent": 3.857
     },
     {
      "finding": "hard exudate",
      "count": 86,
      "per_quadrant": {
       "superior": 50,
       "inferior": 3,
       "nasal": 11,
       "temporal": 22
      },
      "area_percent": 1.333
     },
     {
      "finding": "soft exudate",
      "count": 9,
      "per_quadrant": {
       "superior": 1,
       "inferior": 1,
       "nasal": 7
      },
      "area_percent": 1.049
     }
    ],
    "criteria": [
     "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
     "More than microaneurysms alone but less than severe NPDR: 33 microaneurysms, 48 haemorrhages, 86 hard-exudate focus/foci, 9 cotton-wool spots."
    ],
    "macula": "25 hard-exudate focus/foci within 1 disc diameter of the fovea - clinically significant macular oedema likely; urgent referral."
   },
   "stages": [
    {
     "stage": "1",
     "key": "geometry",
     "ms": 145.6
    },
    {
     "stage": "2",
     "key": "quality",
     "ms": 27.2
    },
    {
     "stage": "3",
     "key": "enhancement",
     "ms": 87.3
    },
    {
     "stage": "3",
     "key": "quality_recheck",
     "ms": 31.1
    },
    {
     "stage": "4",
     "key": "landmarks",
     "ms": 72.4
    },
    {
     "stage": "5",
     "key": "segmentation",
     "ms": 127.5
    },
    {
     "stage": "6",
     "key": "clinical_features",
     "ms": 38.4
    },
    {
     "stage": "7b",
     "key": "grading",
     "ms": 97.6
    },
    {
     "stage": "9",
     "key": "explanation",
     "ms": 34.1
    }
   ],
   "totalMs": 697.7,
   "modelVersion": "drscreen-1.0.0"
  },
  {
   "id": "grade3_case1",
   "image": "../outputs/verification_set/images/grade3_case1.jpg",
   "panel": "../outputs/verification_set/reports/grade3_case1_panel.png",
   "report": "../outputs/verification_set/reports/grade3_case1_report.html",
   "source": "IDRiD",
   "px": [
    1280,
    850
   ],
   "trueGrade": 3,
   "grade": 3,
   "gradeLabel": "Severe NPDR",
   "classProbs": [
    0.0143,
    0.0042,
    0.0899,
    0.8333,
    0.0583
   ],
   "referable": true,
   "referableP": 0.989,
   "sightThreatP": 0.8916,
   "confidence": 0.8333,
   "entropy": 0.618,
   "epistemic": 0.00189,
   "decision": "refer",
   "urgency": "urgent",
   "dmeRisk": 2,
   "quality": {
    "overall": "good",
    "gradeable": true,
    "confidence": 0.801,
    "scores": {
     "focus": 0.6847,
     "illumination": 0.6516,
     "contrast": 0.9112,
     "fov": 0.9441,
     "macula": 0.7499,
     "artifact": 1.0,
     "under_exposure": 0.9455,
     "over_exposure": 1.0,
     "noise": 1.0
    },
    "verdicts": {
     "focus": "pass",
     "illumination": "pass",
     "contrast": "pass",
     "fov": "pass",
     "macula": "pass",
     "artifact": "pass",
     "under_exposure": "pass",
     "over_exposure": "pass",
     "noise": "pass"
    },
    "issues": [],
    "advice": []
   },
   "enhancement": [
    "grey_world"
   ],
   "landmarks": {
    "discConf": 1.0,
    "foveaConf": 0.4443,
    "laterality": "OS",
    "discDiameterPx": 70.9
   },
   "counts": {
    "microaneurysm": 28,
    "hemorrhage": 39,
    "hard_exudate": 14,
    "soft_exudate": 10,
    "neovascularization": 1
   },
   "perQuadrant": {
    "microaneurysm": {
     "superior": 7,
     "inferior": 3,
     "nasal": 5,
     "temporal": 13
    },
    "hemorrhage": {
     "superior": 8,
     "inferior": 7,
     "nasal": 9,
     "temporal": 15
    },
    "hard_exudate": {
     "superior": 6,
     "inferior": 4,
     "nasal": 1,
     "temporal": 3
    },
    "soft_exudate": {
     "superior": 2,
     "inferior": 3,
     "nasal": 4,
     "temporal": 1
    },
    "neovascularization": {
     "superior": 0,
     "inferior": 0,
     "nasal": 1,
     "temporal": 0
    }
   },
   "nearestLesionDD": 0.28,
   "lesionsNearFovea": 11,
   "quadrantsWithHaem": 1,
   "ruleGrade": 2,
   "ruleReasons": [
    "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
    "More than microaneurysms alone but less than severe NPDR: 28 microaneurysms, 39 haemorrhages, 14 hard-exudate focus/foci, 10 cotton-wool spots."
   ],
   "agreement": "within_one_grade",
   "recapture": [],
   "evidence": {
    "findings": [
     {
      "finding": "neovascularization",
      "status": "not assessed",
      "detail": "no pixel supervision for this class in the training corpus; absence of a detection is not evidence of absence of the lesion."
     },
     {
      "finding": "microaneurysm",
      "count": 28,
      "per_quadrant": {
       "superior": 7,
       "inferior": 3,
       "nasal": 5,
       "temporal": 13
      },
      "area_percent": 0.131
     },
     {
      "finding": "hemorrhage",
      "count": 39,
      "per_quadrant": {
       "superior": 8,
       "inferior": 7,
       "nasal": 9,
       "temporal": 15
      },
      "area_percent": 2.477
     },
     {
      "finding": "hard exudate",
      "count": 14,
      "per_quadrant": {
       "superior": 6,
       "inferior": 4,
       "nasal": 1,
       "temporal": 3
      },
      "area_percent": 0.147
     },
     {
      "finding": "soft exudate",
      "count": 10,
      "per_quadrant": {
       "superior": 2,
       "inferior": 3,
       "nasal": 4,
       "temporal": 1
      },
      "area_percent": 1.146
     }
    ],
    "criteria": [
     "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
     "More than microaneurysms alone but less than severe NPDR: 28 microaneurysms, 39 haemorrhages, 14 hard-exudate focus/foci, 10 cotton-wool spots."
    ],
    "macula": "5 hard-exudate focus/foci within 1 disc diameter of the fovea - clinically significant macular oedema likely; urgent referral."
   },
   "stages": [
    {
     "stage": "1",
     "key": "geometry",
     "ms": 135.7
    },
    {
     "stage": "2",
     "key": "quality",
     "ms": 43.5
    },
    {
     "stage": "3",
     "key": "enhancement",
     "ms": 16.8
    },
    {
     "stage": "3",
     "key": "quality_recheck",
     "ms": 25.0
    },
    {
     "stage": "4",
     "key": "landmarks",
     "ms": 64.3
    },
    {
     "stage": "5",
     "key": "segmentation",
     "ms": 120.4
    },
    {
     "stage": "6",
     "key": "clinical_features",
     "ms": 29.8
    },
    {
     "stage": "7b",
     "key": "grading",
     "ms": 79.6
    },
    {
     "stage": "9",
     "key": "explanation",
     "ms": 30.2
    }
   ],
   "totalMs": 563.4,
   "modelVersion": "drscreen-1.0.0"
  },
  {
   "id": "grade3_case2",
   "image": "../outputs/verification_set/images/grade3_case2.jpg",
   "panel": "../outputs/verification_set/reports/grade3_case2_panel.png",
   "report": "../outputs/verification_set/reports/grade3_case2_report.html",
   "source": "APTOS-2019",
   "px": [
    1280,
    920
   ],
   "trueGrade": 3,
   "grade": 3,
   "gradeLabel": "Severe NPDR",
   "classProbs": [
    0.0096,
    0.0038,
    0.1062,
    0.813,
    0.0673
   ],
   "referable": true,
   "referableP": 0.989,
   "sightThreatP": 0.8804,
   "confidence": 0.813,
   "entropy": 0.6541,
   "epistemic": 0.00087,
   "decision": "refer",
   "urgency": "urgent",
   "dmeRisk": 2,
   "quality": {
    "overall": "good",
    "gradeable": true,
    "confidence": 0.7462,
    "scores": {
     "focus": 0.5268,
     "illumination": 0.6929,
     "contrast": 0.8761,
     "fov": 0.913,
     "macula": 0.9071,
     "artifact": 1.0,
     "under_exposure": 1.0,
     "over_exposure": 1.0,
     "noise": 0.8621
    },
    "verdicts": {
     "focus": "pass",
     "illumination": "pass",
     "contrast": "pass",
     "fov": "pass",
     "macula": "pass",
     "artifact": "pass",
     "under_exposure": "pass",
     "over_exposure": "pass",
     "noise": "pass"
    },
    "issues": [],
    "advice": []
   },
   "enhancement": [
    "grey_world",
    "clahe_lab"
   ],
   "landmarks": {
    "discConf": 1.0,
    "foveaConf": 0.7935,
    "laterality": "OD",
    "discDiameterPx": 62.0
   },
   "counts": {
    "microaneurysm": 55,
    "hemorrhage": 82,
    "hard_exudate": 157,
    "soft_exudate": 6,
    "neovascularization": 1
   },
   "perQuadrant": {
    "microaneurysm": {
     "superior": 16,
     "inferior": 8,
     "nasal": 8,
     "temporal": 23
    },
    "hemorrhage": {
     "superior": 19,
     "inferior": 14,
     "nasal": 10,
     "temporal": 39
    },
    "hard_exudate": {
     "superior": 65,
     "inferior": 28,
     "nasal": 23,
     "temporal": 41
    },
    "soft_exudate": {
     "superior": 1,
     "inferior": 2,
     "nasal": 0,
     "temporal": 3
    },
    "neovascularization": {
     "superior": 1,
     "inferior": 0,
     "nasal": 0,
     "temporal": 0
    }
   },
   "nearestLesionDD": 0.3,
   "lesionsNearFovea": 56,
   "quadrantsWithHaem": 3,
   "ruleGrade": 2,
   "ruleReasons": [
    "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
    "More than microaneurysms alone but less than severe NPDR: 55 microaneurysms, 82 haemorrhages, 157 hard-exudate focus/foci, 6 cotton-wool spots."
   ],
   "agreement": "within_one_grade",
   "recapture": [],
   "evidence": {
    "findings": [
     {
      "finding": "neovascularization",
      "status": "not assessed",
      "detail": "no pixel supervision for this class in the training corpus; absence of a detection is not evidence of absence of the lesion."
     },
     {
      "finding": "microaneurysm",
      "count": 55,
      "per_quadrant": {
       "superior": 16,
       "inferior": 8,
       "nasal": 8,
       "temporal": 23
      },
      "area_percent": 0.246
     },
     {
      "finding": "hemorrhage",
      "count": 82,
      "per_quadrant": {
       "superior": 19,
       "inferior": 14,
       "nasal": 10,
       "temporal": 39
      },
      "area_percent": 6.004
     },
     {
      "finding": "hard exudate",
      "count": 157,
      "per_quadrant": {
       "superior": 65,
       "inferior": 28,
       "nasal": 23,
       "temporal": 41
      },
      "area_percent": 2.455
     },
     {
      "finding": "soft exudate",
      "count": 6,
      "per_quadrant": {
       "superior": 1,
       "inferior": 2,
       "temporal": 3
      },
      "area_percent": 0.506
     }
    ],
    "criteria": [
     "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
     "More than microaneurysms alone but less than severe NPDR: 55 microaneurysms, 82 haemorrhages, 157 hard-exudate focus/foci, 6 cotton-wool spots."
    ],
    "macula": "48 hard-exudate focus/foci within 1 disc diameter of the fovea - clinically significant macular oedema likely; urgent referral."
   },
   "stages": [
    {
     "stage": "1",
     "key": "geometry",
     "ms": 116.1
    },
    {
     "stage": "2",
     "key": "quality",
     "ms": 35.0
    },
    {
     "stage": "3",
     "key": "enhancement",
     "ms": 25.5
    },
    {
     "stage": "3",
     "key": "quality_recheck",
     "ms": 31.3
    },
    {
     "stage": "4",
     "key": "landmarks",
     "ms": 64.6
    },
    {
     "stage": "5",
     "key": "segmentation",
     "ms": 140.9
    },
    {
     "stage": "6",
     "key": "clinical_features",
     "ms": 43.6
    },
    {
     "stage": "7b",
     "key": "grading",
     "ms": 89.3
    },
    {
     "stage": "9",
     "key": "explanation",
     "ms": 30.1
    }
   ],
   "totalMs": 598.0,
   "modelVersion": "drscreen-1.0.0"
  },
  {
   "id": "grade4_case1",
   "image": "../outputs/verification_set/images/grade4_case1.jpg",
   "panel": "../outputs/verification_set/reports/grade4_case1_panel.png",
   "report": "../outputs/verification_set/reports/grade4_case1_report.html",
   "source": "APTOS-2019",
   "px": [
    1280,
    920
   ],
   "trueGrade": 4,
   "grade": 4,
   "gradeLabel": "Proliferative DR",
   "classProbs": [
    0.0079,
    0.0049,
    0.0185,
    0.0137,
    0.9549
   ],
   "referable": true,
   "referableP": 0.989,
   "sightThreatP": 0.9686,
   "confidence": 0.9549,
   "entropy": 0.2412,
   "epistemic": 0.00039,
   "decision": "refer",
   "urgency": "urgent",
   "dmeRisk": 2,
   "quality": {
    "overall": "good",
    "gradeable": true,
    "confidence": 0.73,
    "scores": {
     "focus": 0.5122,
     "illumination": 0.8247,
     "contrast": 0.7267,
     "fov": 0.9131,
     "macula": 0.7855,
     "artifact": 1.0,
     "under_exposure": 0.8,
     "over_exposure": 1.0,
     "noise": 1.0
    },
    "verdicts": {
     "focus": "pass",
     "illumination": "pass",
     "contrast": "pass",
     "fov": "pass",
     "macula": "pass",
     "artifact": "pass",
     "under_exposure": "pass",
     "over_exposure": "pass",
     "noise": "pass"
    },
    "issues": [],
    "advice": []
   },
   "enhancement": [
    "grey_world"
   ],
   "landmarks": {
    "discConf": 1.0,
    "foveaConf": 0.5234,
    "laterality": "OS",
    "discDiameterPx": 51.5
   },
   "counts": {
    "microaneurysm": 94,
    "hemorrhage": 70,
    "hard_exudate": 120,
    "soft_exudate": 1,
    "neovascularization": 3
   },
   "perQuadrant": {
    "microaneurysm": {
     "superior": 14,
     "inferior": 23,
     "nasal": 16,
     "temporal": 41
    },
    "hemorrhage": {
     "superior": 9,
     "inferior": 14,
     "nasal": 10,
     "temporal": 37
    },
    "hard_exudate": {
     "superior": 15,
     "inferior": 45,
     "nasal": 4,
     "temporal": 56
    },
    "soft_exudate": {
     "superior": 0,
     "inferior": 0,
     "nasal": 0,
     "temporal": 1
    },
    "neovascularization": {
     "superior": 0,
     "inferior": 0,
     "nasal": 0,
     "temporal": 3
    }
   },
   "nearestLesionDD": 0.26,
   "lesionsNearFovea": 26,
   "quadrantsWithHaem": 4,
   "ruleGrade": 3,
   "ruleReasons": [
    "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
    "20 or more haemorrhages/microaneurysms in each of 4 quadrants (4-2-1 rule, '4')."
   ],
   "agreement": "within_one_grade",
   "recapture": [],
   "evidence": {
    "findings": [
     {
      "finding": "neovascularization",
      "status": "not assessed",
      "detail": "no pixel supervision for this class in the training corpus; absence of a detection is not evidence of absence of the lesion."
     },
     {
      "finding": "microaneurysm",
      "count": 94,
      "per_quadrant": {
       "superior": 14,
       "inferior": 23,
       "nasal": 16,
       "temporal": 41
      },
      "area_percent": 0.502
     },
     {
      "finding": "hemorrhage",
      "count": 70,
      "per_quadrant": {
       "superior": 9,
       "inferior": 14,
       "nasal": 10,
       "temporal": 37
      },
      "area_percent": 5.96
     },
     {
      "finding": "hard exudate",
      "count": 120,
      "per_quadrant": {
       "superior": 15,
       "inferior": 45,
       "nasal": 4,
       "temporal": 56
      },
      "area_percent": 1.669
     },
     {
      "finding": "soft exudate",
      "count": 1,
      "per_quadrant": {
       "temporal": 1
      },
      "area_percent": 0.076
     }
    ],
    "criteria": [
     "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
     "20 or more haemorrhages/microaneurysms in each of 4 quadrants (4-2-1 rule, '4')."
    ],
    "macula": "2 hard-exudate focus/foci within 1 disc diameter of the fovea - clinically significant macular oedema likely; urgent referral."
   },
   "stages": [
    {
     "stage": "1",
     "key": "geometry",
     "ms": 124.4
    },
    {
     "stage": "2",
     "key": "quality",
     "ms": 36.3
    },
    {
     "stage": "3",
     "key": "enhancement",
     "ms": 20.9
    },
    {
     "stage": "3",
     "key": "quality_recheck",
     "ms": 33.0
    },
    {
     "stage": "4",
     "key": "landmarks",
     "ms": 60.5
    },
    {
     "stage": "5",
     "key": "segmentation",
     "ms": 128.2
    },
    {
     "stage": "6",
     "key": "clinical_features",
     "ms": 32.5
    },
    {
     "stage": "7b",
     "key": "grading",
     "ms": 100.0
    },
    {
     "stage": "9",
     "key": "explanation",
     "ms": 31.2
    }
   ],
   "totalMs": 599.8,
   "modelVersion": "drscreen-1.0.0"
  },
  {
   "id": "grade4_case2",
   "image": "../outputs/verification_set/images/grade4_case2.jpg",
   "panel": "../outputs/verification_set/reports/grade4_case2_panel.png",
   "report": "../outputs/verification_set/reports/grade4_case2_report.html",
   "source": "IDRiD",
   "px": [
    1280,
    850
   ],
   "trueGrade": 4,
   "grade": 4,
   "gradeLabel": "Proliferative DR",
   "classProbs": [
    0.027,
    0.0449,
    0.1852,
    0.0294,
    0.7136
   ],
   "referable": true,
   "referableP": 0.8824,
   "sightThreatP": 0.743,
   "confidence": 0.7136,
   "entropy": 0.8934,
   "epistemic": 0.00509,
   "decision": "refer",
   "urgency": "urgent",
   "dmeRisk": 2,
   "quality": {
    "overall": "good",
    "gradeable": true,
    "confidence": 0.7753,
    "scores": {
     "focus": 0.66,
     "illumination": 0.6529,
     "contrast": 0.733,
     "fov": 0.9443,
     "macula": 0.7246,
     "artifact": 1.0,
     "under_exposure": 1.0,
     "over_exposure": 1.0,
     "noise": 1.0
    },
    "verdicts": {
     "focus": "pass",
     "illumination": "pass",
     "contrast": "pass",
     "fov": "pass",
     "macula": "pass",
     "artifact": "pass",
     "under_exposure": "pass",
     "over_exposure": "pass",
     "noise": "pass"
    },
    "issues": [],
    "advice": []
   },
   "enhancement": [
    "grey_world"
   ],
   "landmarks": {
    "discConf": 1.0,
    "foveaConf": 0.388,
    "laterality": "OS",
    "discDiameterPx": 66.0
   },
   "counts": {
    "microaneurysm": 5,
    "hemorrhage": 30,
    "hard_exudate": 46,
    "soft_exudate": 2,
    "neovascularization": 1
   },
   "perQuadrant": {
    "microaneurysm": {
     "superior": 0,
     "inferior": 3,
     "nasal": 2,
     "temporal": 0
    },
    "hemorrhage": {
     "superior": 9,
     "inferior": 9,
     "nasal": 5,
     "temporal": 7
    },
    "hard_exudate": {
     "superior": 4,
     "inferior": 19,
     "nasal": 18,
     "temporal": 5
    },
    "soft_exudate": {
     "superior": 0,
     "inferior": 0,
     "nasal": 1,
     "temporal": 1
    },
    "neovascularization": {
     "superior": 0,
     "inferior": 0,
     "nasal": 1,
     "temporal": 0
    }
   },
   "nearestLesionDD": 0.26,
   "lesionsNearFovea": 17,
   "quadrantsWithHaem": 0,
   "ruleGrade": 2,
   "ruleReasons": [
    "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
    "More than microaneurysms alone but less than severe NPDR: 5 microaneurysms, 30 haemorrhages, 46 hard-exudate focus/foci, 2 cotton-wool spots."
   ],
   "agreement": "disagree",
   "recapture": [],
   "evidence": {
    "findings": [
     {
      "finding": "neovascularization",
      "status": "not assessed",
      "detail": "no pixel supervision for this class in the training corpus; absence of a detection is not evidence of absence of the lesion."
     },
     {
      "finding": "microaneurysm",
      "count": 5,
      "per_quadrant": {
       "inferior": 3,
       "nasal": 2
      },
      "area_percent": 0.023
     },
     {
      "finding": "hemorrhage",
      "count": 30,
      "per_quadrant": {
       "superior": 9,
       "inferior": 9,
       "nasal": 5,
       "temporal": 7
      },
      "area_percent": 2.336
     },
     {
      "finding": "hard exudate",
      "count": 46,
      "per_quadrant": {
       "superior": 4,
       "inferior": 19,
       "nasal": 18,
       "temporal": 5
      },
      "area_percent": 2.484
     },
     {
      "finding": "soft exudate",
      "count": 2,
      "per_quadrant": {
       "nasal": 1,
       "temporal": 1
      },
      "area_percent": 0.271
     }
    ],
    "criteria": [
     "Neovascularisation NOT ASSESSED - no pixel supervision for this class in the training corpus, so proliferative DR cannot be excluded by lesion evidence.",
     "More than microaneurysms alone but less than severe NPDR: 5 microaneurysms, 30 haemorrhages, 46 hard-exudate focus/foci, 2 cotton-wool spots."
    ],
    "macula": "10 hard-exudate focus/foci within 1 disc diameter of the fovea - clinically significant macular oedema likely; urgent referral."
   },
   "stages": [
    {
     "stage": "1",
     "key": "geometry",
     "ms": 132.0
    },
    {
     "stage": "2",
     "key": "quality",
     "ms": 45.8
    },
    {
     "stage": "3",
     "key": "enhancement",
     "ms": 14.1
    },
    {
     "stage": "3",
     "key": "quality_recheck",
     "ms": 33.3
    },
    {
     "stage": "4",
     "key": "landmarks",
     "ms": 58.9
    },
    {
     "stage": "5",
     "key": "segmentation",
     "ms": 137.2
    },
    {
     "stage": "6",
     "key": "clinical_features",
     "ms": 35.6
    },
    {
     "stage": "7b",
     "key": "grading",
     "ms": 86.0
    },
    {
     "stage": "9",
     "key": "explanation",
     "ms": 42.3
    }
   ],
   "totalMs": 620.4,
   "modelVersion": "drscreen-1.0.0"
  }
 ]
};
